#os: linux
#language: php
#php:
#  - 5.5
#  - 5.6
#  - 7.0
#  - 7.1
#  - 7.2
#  - 7.3
#  - 7.4

jobs:
  include:
    - stage: test-53
      language: php
      os: linux
      dist: precise
      php: 5.3
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - mkdir ./composer-test/test-53 && cd ./composer-test/test-53
        - composer init --no-interaction
    - stage: test-54
      language: php
      os: linux
      dist: trusty
      php: 5.4
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - mkdir ./composer-test/test-54 && cd ./composer-test/test-54
        - composer init --no-interaction
    - stage: test-55
      language: php
      os: linux
      dist: trusty
      php: 5.5
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - mkdir ./composer-test/test-55 && cd ./composer-test/test-55
        - composer init --no-interaction
    - stage: test-56
      language: php
      os: linux
      dist: xenial
      php: 5.6
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - mkdir ./composer-test/test-56 && cd ./composer-test/test-56
        - composer init --no-interaction

#before_script:
#  - composer self-update
#  - composer install --dev --optimize-autoloader --no-interaction
#
#script:
#  - ./vendor/bin/phpunit

notifications:
  email:
    on_success: always
    on_failure: always
