os: linux
language: php
php:
  - 5.3.2
  - 5.4.0
  - 5.5.0
  - 5.6.0
  - 7.0.0
  - 7.1.0
  - 7.2.0
  - 7.3.0
  - 7.4.0

before_script:
  - composer self-update
  - composer install --dev --optimize-autoloader --no-interaction

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    on_success: always
    on_failure: always
