jobs:
  include:
    - stage: feature-test
      name: "Feature Test"
      os: linux
      dist: bionic
      language: php
      php: 7.4
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
        - composer self-update
        - composer install --dev --optimize-autoloader --no-interaction
      script:
        - cp ./phpunit.default.xml phpunit.xml
        - ./vendor/bin/phpunit
    - stage: install-test-53
      name: "Test in PHP 5.3"
      os: linux
      dist: precise
      language: php
      php: 5.3
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-53
        - mkdir -p ./composer-test/test-53 && cd ./composer-test/test-53
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php
    - stage: install-test-54
      name: "Test in PHP 5.4"
      os: linux
      dist: trusty
      language: php
      php: 5.4
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-54
        - mkdir -p ./composer-test/test-54 && cd ./composer-test/test-54
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php
    - stage: install-test-55
      name: "Test in PHP 5.5"
      os: linux
      dist: trusty
      language: php
      php: 5.5
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-55
        - mkdir -p ./composer-test/test-55 && cd ./composer-test/test-55
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php
    - stage: install-test-56
      name: "Test in PHP 5.6"
      os: linux
      dist: xenial
      language: php
      php: 5.6
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-56
        - mkdir -p ./composer-test/test-56 && cd ./composer-test/test-56
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php
    - stage: install-test-70
      name: "Test in PHP 7.0"
      os: linux
      dist: xenial
      language: php
      php: 7.0
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-70
        - mkdir -p ./composer-test/test-70 && cd ./composer-test/test-70
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php
    - stage: install-test-71
      name: "Test in PHP 7.1"
      os: linux
      dist: xenial
      language: php
      php: 7.1
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-71
        - mkdir -p ./composer-test/test-71 && cd ./composer-test/test-71
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php
    - stage: install-test-72
      name: "Test in PHP 7.2"
      os: linux
      dist: xenial
      language: php
      php: 7.2
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-72
        - mkdir -p ./composer-test/test-72 && cd ./composer-test/test-72
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php
    - stage: install-test-73
      name: "Test in PHP 7.3"
      os: linux
      dist: xenial
      language: php
      php: 7.3
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-73
        - mkdir -p ./composer-test/test-73 && cd ./composer-test/test-73
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php
    - stage: install-test-74
      name: "Test in PHP 7.4"
      os: linux
      dist: bionic
      language: php
      php: 7.4
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-74
        - mkdir -p ./composer-test/test-74 && cd ./composer-test/test-74
        - composer init --no-interaction
        - composer require saralsms/sdk-for-php

branches:
  only:
    - master
    - develop
    - test

notifications:
  email:
    on_success: always
    on_failure: always
