name: Install
on:
  push:
    # filter branches
    branches:
      - master
      - develop
  schedule:
    # Run everyday UTC/3:15AM
    - cron:  '15 3 * * *'

jobs:
  test:
    # Current OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # OS list
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        # Supported PHP versions
        php: ['7.2', '7.3', '7.4']
    steps:
      # action for repository checkout
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Update composer
        run: sudo composer self-update

      - name: Version info
        run: php --version && composer --version

      - name: Init composer
        run: composer init --no-interaction --stability=dev

      - name: Install SaralSMS package
        run: composer require saralsms/sdk-for-php
